name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:   
    - cron: '0 12 * * *'

jobs:
  build:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.2
    - name: Use Node.js 14
      uses: actions/setup-node@v2.5.2
      with:
        node-version: 14
        cache: 'npm'
    - run: npm install      
    - run: npm test

  sonarcloud:
    name: Run SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0  
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: 16 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9.1      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}